### ISSUE TITLE
function should follow snake case not camel case

### ISSUE THREAD

**Issue by jellyDean** [TimMakingMoves/Messin#1]
https://github.com/TimMakingMoves/Messin/blob/b324d20e26bfbac9c475c626326e39029e09dab6/str_mixup.py#L13

**Comment by jellyDean** [comment]
I might be wrong on this

**Comment by TimMakingMoves** [comment]
https://www.python.org/dev/peps/pep-0008/#function-and-variable-names <-- apparently lowercase with underscores!
